Update target and CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,7 +29,7 @@ jobs:
     
     - name: Install Rust target for wasm
       run: |
-        rustup target add wasm32-wasi
+        rustup target add wasm32-wasip1
         
     - name: Install WasmEdge
       run: |
@@ -39,16 +39,16 @@ jobs:
     - name: sales_tax_rate
       run: |
         cd sales_tax_rate
-        cargo build --target wasm32-wasi --release
-        wasmedgec target/wasm32-wasi/release/sales_tax_rate_lookup.wasm sales_tax_rate_lookup.wasm
+        cargo build --target wasm32-wasip1 --release
+        wasmedgec target/wasm32-wasip1/release/sales_tax_rate_lookup.wasm sales_tax_rate_lookup.wasm
         nohup wasmedge sales_tax_rate_lookup.wasm &
         echo $! > sales_tax_rate.pid
 
     - name: order_total
       run: |
         cd order_total
-        cargo build --target wasm32-wasi --release
-        wasmedgec target/wasm32-wasi/release/order_total.wasm order_total.wasm
+        cargo build --target wasm32-wasip1 --release
+        wasmedgec target/wasm32-wasip1/release/order_total.wasm order_total.wasm
         nohup wasmedge --env "SALES_TAX_RATE_SERVICE=http://127.0.0.1:8001/find_rate" order_total.wasm &
         echo $! > order_total.pid
 
@@ -58,6 +58,15 @@ jobs:
         resp=$(curl http://localhost:8002/compute -X POST -d @order.json)
         echo "$resp"
         if [[ $resp == *"21.65"* ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          exit 1
+        fi
+        sleep 5
+        resp=$(curl http://localhost:8002/compute -X POST -d @order_bad_zip.json)
+        echo "$resp"
+        if [[ $resp == *'"status":"error"'* ]]; then
           echo -e "Execution Success!"
         else
           echo -e "Execution Fail!"
